server:
  port: 8082

spring:
  application:
    name: SWIGGY-APP

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


#FOR WEB_CLIENT
restaurantService:
  base:
    url: http://RESTAURANT-SERVICE/restaurant